name: ${pluginName}
version: ${git.commit.id.abbrev}
main: com.mystiflow.worldborder.WorldBorderPlugin
description: ${project.description}
author: Mystiflow
website: https://github.com/Mystiflow/WorldBorder/

